"""Build the curated static site for both branch-root and Actions Pages publishing."""
from __future__ import annotations

import argparse
import json
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE_FILES = (
    "index.html", "overview.html", "flower.html", "resources.html",
    "archive-brief.html", "archive-introduction.html", "portal.css", "portal.js",
    "flower-demo.json",
)
ROUTES = {
    "overview": "overview.html",
    "flower": "flower.html",
    "resources": "resources.html",
    "brief": "archive-brief.html",
    "introduction": "archive-introduction.html",
}
# Legacy Pages runs Jekyll against the repository root. Do not disable Jekyll:
# these exclusions keep research code and raw evidence out of that website.
EXCLUDED_ROOTS = (
    "archieve", "artifacts", "cache", "contracts", "docker", "node_modules",
    "redteam", "rsi4safety", "scripts", "src", "sut", "tests", "README.md",
    "pytest.ini", "requirements-dev.txt",
)


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.references = []
        self.ids = []
        self.routes = {}

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if "id" in attrs:
            self.ids.append(attrs["id"])
        if tag in {"a", "link"} and "href" in attrs:
            self.references.append(attrs["href"])
        if tag in {"script", "iframe", "img"} and "src" in attrs:
            self.references.append(attrs["src"])
        if "data-route" in attrs and tag == "a":
            self.routes[attrs["data-route"]] = attrs.get("href", "")


def validate_sources(root: Path) -> dict[str, bytes]:
    if (root / ".nojekyll").exists():
        raise ValueError(".nojekyll would bypass the branch-root publication exclusions")
    site = root / "docs" / "site"
    sources = {}
    for name in SITE_FILES:
        source = site / name
        if source.is_symlink() or not source.is_file():
            raise ValueError(f"Missing or linked site source: {name}")
        sources[name] = source.read_bytes()
    for name, data in sources.items():
        if not name.endswith(".html"):
            continue
        parser = Links()
        parser.feed(data.decode("utf-8"))
        if len(parser.ids) != len(set(parser.ids)):
            raise ValueError(f"Duplicate HTML IDs: {name}")
        for ref in parser.references:
            if not ref or ref.startswith(("#", "https://", "http://", "data:", "mailto:")):
                continue
            local = ref.split("#", 1)[0].split("?", 1)[0]
            if local.startswith("./"):
                local = local[2:]
            if local and local not in sources:
                raise ValueError(f"Unpublished local reference in {name}: {ref}")
        if name == "index.html":
            if parser.routes != ROUTES:
                raise ValueError("Portal menus must cover every curated route")
    demo = json.loads(sources["flower-demo.json"])
    if demo.get("protocol") != "redteam-flower-demo-v1" or demo.get("synthetic") is not True:
        raise ValueError("Only synthetic Flower snapshots may be published")
    if demo.get("network") != {"name": "hardhat", "chainId": 31337, "forked": False}:
        raise ValueError("Flower public presentation cannot claim a public-chain deployment")
    if len(demo.get("snapshots", [])) != 2 or demo["snapshots"][0]["tokenId"] != demo["snapshots"][1]["tokenId"]:
        raise ValueError("Flower snapshots must describe one local token")
    return sources


def root_portal(source: bytes) -> bytes:
    text = source.decode("utf-8")
    replacements = {
        'href="portal.css"': 'href="./docs/site/portal.css"',
        'src="portal.js"': 'src="./docs/site/portal.js"',
        'data-page-root="./"': 'data-page-root="./docs/site/"',
    }
    for name in ROUTES.values():
        replacements[f'href="{name}"'] = f'href="./docs/site/{name}"'
    replacements['src="overview.html"'] = 'src="./docs/site/overview.html"'
    for old, new in replacements.items():
        if old not in text:
            raise ValueError(f"Missing root portal generation hook: {old}")
        text = text.replace(old, new)
    return text.encode("utf-8")


def jekyll_config(root: Path) -> bytes:
    excluded = set(EXCLUDED_ROOTS)
    excluded.update(
        entry.name for entry in root.iterdir()
        if not entry.name.startswith((".", "_")) and entry.name not in {"index.html", "docs"}
    )
    excluded.update(f"docs/{entry.name}" for entry in (root / "docs").iterdir() if entry.name != "site")
    lines = [
        "# Generated by scripts/build_site.py for the existing main / Pages source.",
        "title: REDTEAM", 'url: "https://fishman-free.github.io"', 'baseurl: "/REDTEAM"',
        "exclude:",
    ]
    lines.extend(f"  - {json.dumps(name, ensure_ascii=False)}" for name in sorted(excluded))
    return ("\n".join(lines) + "\n").encode("utf-8")


def build(root: Path, *, check: bool = False, output_dir: Path | None = None) -> None:
    sources = validate_sources(root)
    outputs = {"index.html": root_portal(sources["index.html"]), "_config.yml": jekyll_config(root)}
    if output_dir is not None:
        output_dir = output_dir.resolve()
        if output_dir == root.resolve() or output_dir.is_relative_to((root / "docs").resolve()):
            raise ValueError("Bundle destination must not overwrite source files")
        if output_dir.exists() and any(output_dir.iterdir()):
            raise ValueError("Bundle destination must be new or empty")
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "index.html").write_bytes(outputs["index.html"])
        target = output_dir / "docs" / "site"
        target.mkdir(parents=True)
        for name, data in sources.items():
            (target / name).write_bytes(data)
        return
    for name, data in outputs.items():
        target = root / name
        if check:
            if not target.is_file() or target.read_bytes() != data:
                raise ValueError(f"Generated {name} is stale; run python scripts/build_site.py")
        else:
            if target.is_symlink():
                raise ValueError(f"Refusing linked generated file: {name}")
            target.write_bytes(data)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true")
    group.add_argument("--output-dir", type=Path)
    args = parser.parse_args()
    build(ROOT, check=args.check, output_dir=args.output_dir)
    print(f"Validated {len(ROUTES)} menus and {len(SITE_FILES)} allow-listed site assets")


if __name__ == "__main__":
    main()
